### ISSUE TITLE
Add search for finding nodes

### ISSUE THREAD

**Issue by rossicler** [rossicler/enshrouded-skill-tree#17]

**Comment by tomt00001** [comment]
Maybe tags like in path of exile everything has a tag (minions,fire, elemental, caster) than we could use a list of tags to narrow down highlighted skills?

Craft of exile is a reference website for how those tags can be used

**Comment by rossicler** [comment]
That is a good way to approach it, but this game doesn't have many nodes, so actually search through all nodes names and description might also work and still be performant. I'll test it
