### ISSUE TITLE
[Bug] Deselecting a node in the Wizard Branch deselects all/many nodes

### ISSUE THREAD

**Issue by ortegamarcel** [rossicler/enshrouded-skill-tree#22]
Like described in the title. When I deselect a node in the Wizard Branch, all conencted nodes are deselected.

Steps to reproduce:
1. Select nodes like shown in the screenshot
2. Deselect the last "Intelligence"-node from the wizard branch.

![image](https://github.com/rossicler/enshrouded-skill-tree/assets/9929801/2ab225d1-e69a-4dfa-a0cd-87846b5e76d1)

**Comment by rossicler** [comment]
Just tested it out and I see the bug, I'll check it out, thanks for reporting this
